<a href="https://colab.research.google.com/github/gkhan02/datasci_1_loading/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The following code cell below imports pandas and json**

we need pandas because we cannot load our datasets without it

we need json to br able to read files

In [1]:
import pandas as pd

### csv_data1 represents the following:

**General information:**  
This dataset contains national weekly estimates of cumulative COVID-19-associated hospitalizations.

**Columns**

1. **Burden**
   - Identifies the type of health burden being measured, which is hospitalizations.

2. **Season**
   - Shows the respiratory virus season associated with the data.

3. **Date**
   - Shows the date for the reporting week.

4. **Low**
   - Shows the lower estimate of cumulative COVID-19 hospitalizations.

5. **High**
   - Shows the upper estimate of cumulative COVID-19 hospitalizations.

In [3]:
df1 = '/content/Data/covid_hospitalizations.csv'
read_csv1 = pd.read_csv(df1)
read_csv1.head(11)

              Burden     Season        Date     Low     High
0   Hospitalizations  2024-2025  2024-10-05  10,000   17,000
1   Hospitalizations  2024-2025  2024-10-12  20,000   31,000
2   Hospitalizations  2024-2025  2024-10-19  29,000   44,000
3   Hospitalizations  2024-2025  2024-10-26  37,000   55,000
4   Hospitalizations  2024-2025  2024-11-02  44,000   66,000
5   Hospitalizations  2024-2025  2024-11-09  52,000   76,000
6   Hospitalizations  2024-2025  2024-11-16  59,000   86,000
7   Hospitalizations  2024-2025  2024-11-23  67,000   98,000
8   Hospitalizations  2024-2025  2024-11-30  75,000  110,000
9   Hospitalizations  2024-2025  2024-12-07  83,000  120,000
10  Hospitalizations  2024-2025  2024-12-14  91,000  130,000

### Influenza Vaccine Doses Dataset

**General Information:**  
This dataset contains information about influenza vaccine doses distributed in the United States during different influenza seasons.

**Features/Columns:**

1. **Influenza_Season**
   - Identifies the influenza season associated with the vaccine distribution data.

2. **Start_Date**
   - Shows the beginning date of the reporting period.

3. **End_Date**
   - Shows the ending date of the reporting period.

4. **Reporting_TimeFrame**
   - Describes the time period used for reporting the vaccine distribution data.

5. **Week_Sort_Order**
   - Shows the numerical order of the reporting week.

6. **Current_Season_Week_Ending_Label**
   - Shows the ending date of the current reporting week.

7. **Cumulative_Flu_Doses_Distributed**
   - Shows the cumulative number of influenza vaccine doses distributed.

8. **Current_Through**
   - Shows the date through which the information is considered current.

In [8]:
df2 = '/content/Data/flu_vaccine_doses.csv'
read_csv1 = pd.read_csv(df2)
read_csv1.head(11)

,Influenza_Season,Start_Date,End_Date,Reporting_TimeFrame,Week_Sort_Order,Current_Season_Week_Ending_Label,Cumulative_Flu_Doses_Distributed,Current_Through
0,2018-2019,2018 Jul 29 12:00:00 AM,2018 Aug 04 12:00:00 AM,2018-07-29 - 2018-08-04,1,2025 Aug 02 12:00:00 AM,0.52,2023 Mar 04 12:00:00 AM
1,2018-2019,2018 Aug 05 12:00:00 AM,2018 Aug 11 12:00:00 AM,2018-08-05 - 2018-08-11,2,2025 Aug 09 12:00:00 AM,3.23,2023 Mar 04 12:00:00 AM
2,2018-2019,2018 Aug 12 12:00:00 AM,2018 Aug 18 12:00:00 AM,2018-08-12 - 2018-08-18,3,2025 Aug 16 12:00:00 AM,10.18,2023 Mar 04 12:00:00 AM
3,2018-2019,2018 Aug 19 12:00:00 AM,2018 Aug 25 12:00:00 AM,2018-08-19 - 2018-08-25,4,2025 Aug 23 12:00:00 AM,19.99,2023 Mar 04 12:00:00 AM
4,2018-2019,2018 Aug 26 12:00:00 AM,2018 Sep 01 12:00:00 AM,2018-08-26 - 2018-09-01,5,2025 Aug 30 12:00:00 AM,37.38,2023 Mar 04 12:00:00 AM
5,2018-2019,2018 Sep 02 12:00:00 AM,2018 Sep 08 12:00:00 AM,2018-09-02 - 2018-09-08,6,2025 Sep 06 12:00:00 AM,52.23,2023 Mar 04 12:00:00 AM
6,2018-2019,2018 Sep 09 12:00:00 AM,2018 Sep 15 12:00:00 AM,2018-09-09 - 2018-09-15,7,2025 Sep 13 12:00:00 AM,70.39,2023 Mar 04 12:00:00 AM
7,2018-2019,2018 Sep 16 12:00:00 AM,2018 Sep 22 12:00:00 AM,2018-09-16 - 2018-09-22,8,2025 Sep 20 12:00:00 AM,87.79,2023 Mar 04 12:00:00 AM
8,2018-2019,2018 Sep 23 12:00:00 AM,2018 Sep 29 12:00:00 AM,2018-09-23 - 2018-09-29,9,2025 Sep 27 12:00:00 AM,104.38,2023 Mar 04 12:00:00 AM
9,2018-2019,2018 Sep 30 12:00:00 AM,2018 Oct 06 12:00:00 AM,2018-09-30 - 2018-10-06,10,2025 Oct 04 12:00:00 AM,118.80,2023 Mar 04 12:00:00 AM
10,2018-2019,2018 Oct 07 12:00:00 AM,2018 Oct 13 12:00:00 AM,2018-10-07 - 2018-10-13,11,2025 Oct 11 12:00:00 AM,132.57,2023 Mar 04 12:00:00 AM

### RSV Hospitalizations Dataset

**General Information:**  
This dataset contains weekly estimates of cumulative RSV hospitalizations in the United States.

**Features/Columns:**

1. **Burden**
   - Identifies the type of health burden being measured. In this dataset, it represents hospitalizations.

2. **Season**
   - Identifies the respiratory season associated with the hospitalization estimates.

3. **Date**
   - Shows the ending date of the reporting week.

4. **Low**
   - Shows the lower estimate of cumulative RSV hospitalizations.

5. **High**
   - Shows the upper estimate of cumulative RSV hospitalizations.

In [9]:
df3 = '/content/Data/rsv_hospitalizations.csv'
read_csv1 = pd.read_csv(df3)
read_csv1.head(11)

              Burden     Season        Date     Low    High
0   Hospitalizations  2024-2025  2024-10-05     570   1,200
1   Hospitalizations  2024-2025  2024-10-12   1,300   2,600
2   Hospitalizations  2024-2025  2024-10-19   2,300   4,400
3   Hospitalizations  2024-2025  2024-10-26   3,500   6,700
4   Hospitalizations  2024-2025  2024-11-02   5,100   9,600
5   Hospitalizations  2024-2025  2024-11-09   7,400  14,000
6   Hospitalizations  2024-2025  2024-11-16  10,000  19,000
7   Hospitalizations  2024-2025  2024-11-23  14,000  26,000
8   Hospitalizations  2024-2025  2024-11-30  19,000  34,000
9   Hospitalizations  2024-2025  2024-12-07  25,000  45,000
10  Hospitalizations  2024-2025  2024-12-14  33,000  60,000

### U.S. State Life Expectancy Dataset

**General Information:**  
This dataset contains 2021 life expectancy estimates for the United States, the 50 states, and the District of Columbia by sex.

**Features/Columns:**

1. **area**
   - Identifies the state or geographic area represented in the data.

2. **sex**
   - Identifies whether the life expectancy estimate is for males, females, or the total population.

3. **leb**
   - Shows the estimated life expectancy at birth.

4. **se**
   - Shows the standard error of the life expectancy estimate.

5. **quartile**
   - Identifies the life expectancy quartile or range in which the geographic area falls.

In [10]:
df4 = '/content/Data/life_expectancy.json'
read_json1 = pd.read_json(df4)
read_json1.head(11)

,:id,:version,:created_at,:updated_at,area,sex,leb,se,quartile
0,row-ku5q.j2y3.q8p4,rv-qzrk_vx8d.cfbe,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Mississippi,Total,70.9,0.092,70.9 - 74.5
1,row-3i62~2vy9~qq94,rv-ea2e-5zzt.7czs,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,West Virginia,Total,71.0,0.117,70.9 - 74.5
2,row-7ban_bi9p-za7b,rv-zraf~875x_fz8t,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Alabama,Total,72.0,0.069,70.9 - 74.5
3,row-3ayz-wg52-erv5,rv-vjar_mrbk-qsis,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Louisiana,Total,72.2,0.073,70.9 - 74.5
4,row-2326~dkq9-xa94,rv-h37x.ni9r~sdek,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Kentucky,Total,72.3,0.071,70.9 - 74.5
5,row-ihym-wd9q-swme,rv-74zp.hue4~ehsr,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Tennessee,Total,72.4,0.057,70.9 - 74.5
6,row-eh2f~986e-3ttp,rv-cegt.ri8u~iwri,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Arkansas,Total,72.5,0.089,70.9 - 74.5
7,row-hmnk~6dbc~gzf5,rv-3auv~u969_4m3t,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Oklahoma,Total,72.7,0.074,70.9 - 74.5
8,row-ns2q~2cf5.ca3q,rv-rs7p_5bas~zk6k,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,New Mexico,Total,73.0,0.113,70.9 - 74.5
9,row-zm3z-3xpt.eecu,rv-f2dr.mrcg~8jwu,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,South Carolina,Total,73.5,0.069,70.9 - 74.5
10,row-hytv.ix26~74xi,rv-287g_r3dj~kpjw,2024-09-11 10:31:06.954000+00:00,2024-09-11 10:31:06.954000+00:00,Georgia,Total,74.3,0.045,70.9 - 74.5

### Infant Mortality Dataset

**General Information:**  
This dataset contains historical infant mortality rates in the United States by race and year.

**Features/Columns:**

1. **race**
   - Identifies the racial group represented in the record.

2. **year**
   - Shows the year associated with the infant mortality data.

3. **infant_mortality_rate**
   - Shows the infant mortality rate for the specified racial group and year.

In [11]:
df5 = '/content/Data/infant_mortality.json'
read_json2 = pd.read_json(df5)
read_json2.head(11)

,:id,:version,:created_at,:updated_at,race,year,infant_mortality_rate
0,row-y2ra-cmdx-v8pm,rv-8nci-yxa6~a2wn,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1915,195.2
1,row-9dzf_vdnh.ihxp,rv-ghm6.pxcp.7ryc,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1916,184.3
2,row-druv.ey47~99bb,rv-fsxt~rs6q~dnda,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1917,173.4
3,row-hm4c_q5xq-j39a,rv-c2dg.ghc3.nh4p,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1918,162.5
4,row-ipgm.upgk_xch9,rv-vhch.yfzx-vu54,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1919,134.3
5,row-f3rm~ddw5_53mf,rv-78ay_3m8h.yswc,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1920,135.6
6,row-kt39_jb3x~vuid,rv-83jv_veqf-h6vv,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1921,110.7
7,row-r5h5_7aaz.5s8n,rv-hndq~dxu3-6b99,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1922,111.6
8,row-7w99-zkts~5kd4,rv-iwcx.7i48~xnmu,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1923,119.9
9,row-5qs9.sqfx.2fub,rv-xzbr.wbyf_s6wa,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1924,114.1
10,row-sy6g.uhqb_2fcc,rv-sken.dib5_2v8g,2015-12-02 17:37:36.167000+00:00,2015-12-02 17:37:36.167000+00:00,Black,1925,112.0

### U.S. and State Teen Births Dataset

**General Information:**  
This dataset contains information about teen birth rates and numbers of births by state, age group, and year.

**Features/Columns:**

1. **year**
   - Shows the year associated with the birth data.

2. **state**
   - Identifies the state represented in the record.

3. **age_years**
   - Identifies the teenage age group represented in the data.

4. **state_rate**
   - Shows the teen birth rate for the state.

5. **state_births**
   - Shows the number of teen births reported in the state.

6. **u_s_births**
   - Shows the number of teen births in the United States.

7. **u_s_birth_rate**
   - Shows the overall teen birth rate for the United States.

8. **unit**
   - Identifies the unit used to report the birth-rate information.

In [13]:
df6 = '/content/Data/teen_births.json'
read_json3 = pd.read_json(df6)
read_json3.head(11)

,:id,:version,:created_at,:updated_at,year,state,age_years,state_rate,state_births,u_s_births,u_s_birth_rate,unit
0,row-uf9w_uvyj-er2x,rv-f6d5~y4au_dsjn,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Alabama,15-17 years,47.4,4222,183327,37.5,"per 1,000"
1,row-ekau~rvwk.dxhp,rv-78fj-srsj.ih7f,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Alaska,15-17 years,31.2,335,183327,37.5,"per 1,000"
2,row-iskq~gbzv-vh3j,rv-uuru~kqr7_r54u,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Arizona,15-17 years,47.7,3436,183327,37.5,"per 1,000"
3,row-tkrw-gzcv_7eh6,rv-pd6q.wgt9.b4fi,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Arkansas,15-17 years,50.4,2549,183327,37.5,"per 1,000"
4,row-xsbx~7uge.z3cf,rv-ys3t_7nm8_7yjj,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,California,15-17 years,44.6,24880,183327,37.5,"per 1,000"
5,row-j6if-r3wk-dj4t,rv-x3vz~qcr2_k7e4,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Colorado,15-17 years,33.1,2061,183327,37.5,"per 1,000"
6,row-mze5.epzw_tcw7,rv-mcyw_fewz.5nv8,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Connecticut,15-17 years,26.4,1519,183327,37.5,"per 1,000"
7,row-se8c-ipii~8h3s,rv-ztdq.5f6x~4ugv,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Delaware,15-17 years,38.4,462,183327,37.5,"per 1,000"
8,row-b69w-yw6s_nee2,rv-zc2y~wh4s.ce4r,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,District of Columbia,15-17 years,88.4,841,183327,37.5,"per 1,000"
9,row-a638_r4p4_afd7,rv-knev_ajiw.dkfh,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Florida,15-17 years,44.9,9918,183327,37.5,"per 1,000"
10,row-4eaj_nkgr~eju3,rv-wsym~gu4w_2yhg,2022-05-09 14:40:39.900000+00:00,2022-05-09 14:40:39.900000+00:00,1990,Georgia,15-17 years,50.1,6878,183327,37.5,"per 1,000"

### Hepatitis A Dataset

**General Information:**  
This dataset contains rates of reported hepatitis A cases by sex in the United States from 2005 through 2020. Rates are reported per 100,000 population.

**Features/Columns:**

1. **Sex**
   - Identifies whether the reported hepatitis A rate is for males or females.

2. **2005**
   - Shows the reported hepatitis A case rate for 2005.

3. **2006**
   - Shows the reported hepatitis A case rate for 2006.

4. **2007**
   - Shows the reported hepatitis A case rate for 2007.

5. **2008**
   - Shows the reported hepatitis A case rate for 2008.

6. **2009**
   - Shows the reported hepatitis A case rate for 2009.

7. **2010**
   - Shows the reported hepatitis A case rate for 2010.

8. **2011**
   - Shows the reported hepatitis A case rate for 2011.

9. **2012**
   - Shows the reported hepatitis A case rate for 2012.

10. **2013**
    - Shows the reported hepatitis A case rate for 2013.

11. **2014**
    - Shows the reported hepatitis A case rate for 2014.

12. **2015**
    - Shows the reported hepatitis A case rate for 2015.

13. **2016**
    - Shows the reported hepatitis A case rate for 2016.

14. **2017**
    - Shows the reported hepatitis A case rate for 2017.

15. **2018**
    - Shows the reported hepatitis A case rate for 2018.

16. **2019**
    - Shows the reported hepatitis A case rate for 2019.

17. **2020**
    - Shows the reported hepatitis A case rate for 2020.

In [14]:
df7 = '/content/Data/hepatitis_a.xlsx'
read_xlsx1 = pd.read_excel(df7)
read_xlsx1.head(11)

,Unnamed: 0,"Figure 1.5. Rates* of reported cases† of hepatitis A virus infection, by sex — United States, 2005–2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,Sex,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
1,NaN,Male,1.7,1.3,1.1,0.9,0.7,0.6,0.5,0.5,0.6,0.4,0.5,0.7,1.4,4.7,7.3,3.8
2,NaN,Female,1.3,1.1,0.9,0.8,0.6,0.5,0.4,0.5,0.6,0.4,0.4,0.5,0.7,3.0,4.2,2.3
3,NaN,"Source: CDC, National Notifiable Diseases Surv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,"* Rates per 100,000 population.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,† Reported confirmed cases. For the case defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Hepatitis B Dataset

**General Information:**  
This dataset contains rates of reported acute hepatitis B cases by sex in the United States from 2005 through 2020. Rates are reported per 100,000 population.

**Features/Columns:**

1. **Sex**
   - Identifies whether the reported hepatitis B rate is for males or females.

2. **2005**
   - Shows the reported acute hepatitis B case rate for 2005.

3. **2006**
   - Shows the reported acute hepatitis B case rate for 2006.

4. **2007**
   - Shows the reported acute hepatitis B case rate for 2007.

5. **2008**
   - Shows the reported acute hepatitis B case rate for 2008.

6. **2009**
   - Shows the reported acute hepatitis B case rate for 2009.

7. **2010**
   - Shows the reported acute hepatitis B case rate for 2010.

8. **2011**
   - Shows the reported acute hepatitis B case rate for 2011.

9. **2012**
   - Shows the reported acute hepatitis B case rate for 2012.

10. **2013**
    - Shows the reported acute hepatitis B case rate for 2013.

11. **2014**
    - Shows the reported acute hepatitis B case rate for 2014.

12. **2015**
    - Shows the reported acute hepatitis B case rate for 2015.

13. **2016**
    - Shows the reported acute hepatitis B case rate for 2016.

14. **2017**
    - Shows the reported acute hepatitis B case rate for 2017.

15. **2018**
    - Shows the reported acute hepatitis B case rate for 2018.

16. **2019**
    - Shows the reported acute hepatitis B case rate for 2019.

17. **2020**
    - Shows the reported acute hepatitis B case rate for 2020.

In [15]:
df8 = '/content/Data/hepatitis_b.xlsx'
read_xlsx2 = pd.read_excel(df8)
read_xlsx2.head(11)

,Unnamed: 0,"Figure 2.5. Rates* of reported cases† of acute hepatitis B virus infection, by sex — United States, 2005–2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,Sex,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
1,NaN,Male,2.3,2.1,1.9,1.7,1.4,1.4,1.2,1.2,1.2,1.1,1.3,1.2,1.3,1.3,1.3,0.8
2,NaN,Female,1.4,1.1,1.1,1.0,0.8,0.8,0.7,0.7,0.7,0.6,0.8,0.8,0.8,0.8,0.7,0.5
3,NaN,"Source: CDC, National Notifiable Diseases Surv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,"* Rates per 100,000 population.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,† Reported confirmed cases. For the case defi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Hepatitis C Dataset

**General Information:**  
This dataset contains rates of reported acute hepatitis C cases by sex in the United States from 2005 through 2020. Rates are reported per 100,000 population.

**Features/Columns:**

1. **Sex**
   - Identifies whether the reported hepatitis C rate is for males or females.

2. **2005**
   - Shows the reported acute hepatitis C case rate for 2005.

3. **2006**
   - Shows the reported acute hepatitis C case rate for 2006.

4. **2007**
   - Shows the reported acute hepatitis C case rate for 2007.

5. **2008**
   - Shows the reported acute hepatitis C case rate for 2008.

6. **2009**
   - Shows the reported acute hepatitis C case rate for 2009.

7. **2010**
   - Shows the reported acute hepatitis C case rate for 2010.

8. **2011**
   - Shows the reported acute hepatitis C case rate for 2011.

9. **2012**
   - Shows the reported acute hepatitis C case rate for 2012.

10. **2013**
    - Shows the reported acute hepatitis C case rate for 2013.

11. **2014**
    - Shows the reported acute hepatitis C case rate for 2014.

12. **2015**
    - Shows the reported acute hepatitis C case rate for 2015.

13. **2016**
    - Shows the reported acute hepatitis C case rate for 2016.

14. **2017**
    - Shows the reported acute hepatitis C case rate for 2017.

15. **2018**
    - Shows the reported acute hepatitis C case rate for 2018.

16. **2019**
    - Shows the reported acute hepatitis C case rate for 2019.

17. **2020**
    - Shows the reported acute hepatitis C case rate for 2020.

In [17]:
df9 = '/content/Data/hepatitis_c.xlsx'
read_xlsx3 = pd.read_excel(df9)
read_xlsx3.head(11)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,Figure 3.5. Rates* of reported cases† of acute...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Sex,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
2,NaN,Male,0.3,0.3,0.3,0.3,0.3,0.3,0.4,0.7,0.8,0.8,0.9,1.1,1.2,1.3,1.6,2.0
3,NaN,Female,0.2,0.2,0.3,0.3,0.3,0.3,0.4,0.5,0.7,0.7,0.7,0.8,0.9,1.0,1.0,1.0
4,NaN,"Source: CDC, National Notifiable Diseases Surv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,"* Rates per 100,000 population.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,† Reported confirmed cases. For the case defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN